'use strict';

/**
 * Region/country hierarchy, extracted from the APK's own
 * res/raw/l10n_android__regionsgzip_{ru,en} files - see
 * tools/build-regions.js for how this was generated and README.md
 * "RegionCommand real data" for the wire-field derivation
 * (drug.vokrug.system.db.RegionsDB.java's column names).
 *
 * Two levels: COUNTRY (ISO 3166-1 codes, or a calling-code-as-id for
 * ex-USSR/CIS countries - exactly as the app itself does it) at the root,
 * and REGION (Russian federal subjects) as children of Russia (code "0").
 * PHONE_LENGTH is deliberately always 0 - RegionInfo's own display logic
 * treats 0 as "unset" and falls back to a generous 14-digit cap
 * (AnonymousActivity.java), which is safer than fabricating precise
 * national number lengths for 232 countries without a way
 * to verify them.
 */

const COUNTRIES = [
  { code: 'AF', iso: 'AF', prefix: '93', nameRu: 'Афганистан', nameEn: 'Afghanistan' },
  { code: 'AX', iso: 'AX', prefix: '358', nameRu: 'Аландские острова', nameEn: 'Aland Islands' },
  { code: 'AL', iso: 'AL', prefix: '355', nameRu: 'Албания', nameEn: 'Albania' },
  { code: 'DZ', iso: 'DZ', prefix: '213', nameRu: 'Алжир', nameEn: 'Algeria' },
  { code: 'AS', iso: 'AS', prefix: '1', nameRu: 'Американское Самоа', nameEn: 'American Samoa' },
  { code: 'AD', iso: 'AD', prefix: '376', nameRu: 'Андорра', nameEn: 'Andorra' },
  { code: 'AO', iso: 'AO', prefix: '244', nameRu: 'Ангола', nameEn: 'Angola' },
  { code: 'AI', iso: 'AI', prefix: '1', nameRu: 'Ангилья', nameEn: 'Anguilla' },
  { code: 'AG', iso: 'AG', prefix: '1', nameRu: 'Антигуа и Барбуда', nameEn: 'Antigua and Barbuda' },
  { code: 'AR', iso: 'AR', prefix: '54', nameRu: 'Аргентина', nameEn: 'Argentina' },
  { code: 'AM', iso: 'AM', prefix: '374', nameRu: 'Армения', nameEn: 'Armenia' },
  { code: 'AW', iso: 'AW', prefix: '297', nameRu: 'Аруба', nameEn: 'Aruba' },
  { code: 'AU', iso: 'AU', prefix: '61', nameRu: 'Австралия', nameEn: 'Australia' },
  { code: 'AT', iso: 'AT', prefix: '43', nameRu: 'Австрия', nameEn: 'Austria' },
  { code: '994', iso: 'AZ', prefix: '994', nameRu: 'Азербайджан', nameEn: 'Azerbaijan' },
  { code: 'BS', iso: 'BS', prefix: '1', nameRu: 'Багамы', nameEn: 'Bahamas' },
  { code: 'BH', iso: 'BH', prefix: '973', nameRu: 'Бахрейн', nameEn: 'Bahrain' },
  { code: 'BD', iso: 'BD', prefix: '880', nameRu: 'Бангладеш', nameEn: 'Bangladesh' },
  { code: 'BB', iso: 'BB', prefix: '1', nameRu: 'Барбадос', nameEn: 'Barbados' },
  { code: '375', iso: 'BY', prefix: '375', nameRu: 'Белоруссия', nameEn: 'Belarus' },
  { code: 'BE', iso: 'BE', prefix: '32', nameRu: 'Бельгия', nameEn: 'Belgium' },
  { code: 'BZ', iso: 'BZ', prefix: '501', nameRu: 'Белиз', nameEn: 'Belize' },
  { code: 'BJ', iso: 'BJ', prefix: '229', nameRu: 'Бенин', nameEn: 'Benin' },
  { code: 'BM', iso: 'BM', prefix: '1', nameRu: 'Бермуды', nameEn: 'Bermudas' },
  { code: 'BT', iso: 'BT', prefix: '975', nameRu: 'Бутан', nameEn: 'Bhutan' },
  { code: 'BO', iso: 'BO', prefix: '591', nameRu: 'Боливия', nameEn: 'Bolivia' },
  { code: 'BA', iso: 'BA', prefix: '387', nameRu: 'Босния и Герцеговина', nameEn: 'Bosnia and Herzegovina' },
  { code: 'BW', iso: 'BW', prefix: '267', nameRu: 'Ботсвана', nameEn: 'Botswana' },
  { code: 'BR', iso: 'BR', prefix: '55', nameRu: 'Бразилия', nameEn: 'Brazil' },
  { code: 'IO', iso: 'IO', prefix: '246', nameRu: 'Британская территория в Индийском океане', nameEn: 'British Indian Ocean Territory' },
  { code: 'BN', iso: 'BN', prefix: '673', nameRu: 'Бруней', nameEn: 'Brunei Darussalam' },
  { code: 'BG', iso: 'BG', prefix: '359', nameRu: 'Болгария', nameEn: 'Bulgaria' },
  { code: 'BF', iso: 'BF', prefix: '226', nameRu: 'Буркина-Фасо', nameEn: 'Burkina Faso' },
  { code: 'BI', iso: 'BI', prefix: '257', nameRu: 'Бурунди', nameEn: 'Burundi' },
  { code: 'KH', iso: 'KH', prefix: '855', nameRu: 'Камбоджа', nameEn: 'Cambodia' },
  { code: 'CM', iso: 'CM', prefix: '237', nameRu: 'Камерун', nameEn: 'Cameroon' },
  { code: 'CA', iso: 'CA', prefix: '1', nameRu: 'Канада', nameEn: 'Canada' },
  { code: 'CV', iso: 'CV', prefix: '238', nameRu: 'Кабо-Верде', nameEn: 'Cape Verde' },
  { code: 'KY', iso: 'KY', prefix: '1', nameRu: 'Каймановы острова', nameEn: 'Cayman Islands' },
  { code: 'CF', iso: 'CF', prefix: '236', nameRu: 'ЦАР', nameEn: 'Central African Republic' },
  { code: 'TD', iso: 'TD', prefix: '235', nameRu: 'Чад', nameEn: 'Chad' },
  { code: 'CL', iso: 'CL', prefix: '56', nameRu: 'Чили', nameEn: 'Chile' },
  { code: 'CN', iso: 'CN', prefix: '86', nameRu: 'Китай', nameEn: 'China' },
  { code: 'CO', iso: 'CO', prefix: '57', nameRu: 'Колумбия', nameEn: 'Colombia' },
  { code: 'CG', iso: 'CG', prefix: '242', nameRu: 'Конго', nameEn: 'Congo' },
  { code: 'CD', iso: 'CD', prefix: '243', nameRu: 'Дем. Респ. Конго', nameEn: 'Democratic Republic of the Congo' },
  { code: 'CK', iso: 'CK', prefix: '682', nameRu: 'Острова Кука', nameEn: 'Cook Islands' },
  { code: 'CR', iso: 'CR', prefix: '506', nameRu: 'Коста-Рика', nameEn: 'Costa Rica' },
  { code: 'CI', iso: 'CI', prefix: '225', nameRu: 'Кот-д’Ивуар', nameEn: 'Ivory Coast' },
  { code: 'HR', iso: 'HR', prefix: '385', nameRu: 'Хорватия', nameEn: 'Croatia' },
  { code: 'CU', iso: 'CU', prefix: '53', nameRu: 'Куба', nameEn: 'Cuba' },
  { code: 'CY', iso: 'CY', prefix: '357', nameRu: 'Кипр', nameEn: 'Cyprus' },
  { code: 'CZ', iso: 'CZ', prefix: '420', nameRu: 'Чехия', nameEn: 'Czech Republic' },
  { code: 'DK', iso: 'DK', prefix: '45', nameRu: 'Дания', nameEn: 'Denmark' },
  { code: 'DJ', iso: 'DJ', prefix: '253', nameRu: 'Джибути', nameEn: 'Djibouti' },
  { code: 'DO', iso: 'DO', prefix: '1', nameRu: 'Доминиканская Республика', nameEn: 'Dominican Republic' },
  { code: 'EC', iso: 'EC', prefix: '593', nameRu: 'Эквадор', nameEn: 'Ecuador' },
  { code: 'EG', iso: 'EG', prefix: '20', nameRu: 'Египет', nameEn: 'Egypt' },
  { code: 'SV', iso: 'SV', prefix: '503', nameRu: 'Сальвадор', nameEn: 'El Salvador' },
  { code: 'GQ', iso: 'GQ', prefix: '240', nameRu: 'Экваториальная Гвинея', nameEn: 'Equatorial Guinea' },
  { code: 'ER', iso: 'ER', prefix: '291', nameRu: 'Эритрея', nameEn: 'Eritrea' },
  { code: '372', iso: 'EE', prefix: '372', nameRu: 'Эстония', nameEn: 'Estonia' },
  { code: 'ET', iso: 'ET', prefix: '251', nameRu: 'Эфиопия', nameEn: 'Ethiopia' },
  { code: 'EU', iso: 'EU', prefix: '', nameRu: 'Европейский союз', nameEn: 'European Union' },
  { code: 'FO', iso: 'FO', prefix: '298', nameRu: 'Фарерские острова', nameEn: 'Faroe Islands' },
  { code: 'FJ', iso: 'FJ', prefix: '679', nameRu: 'Фиджи', nameEn: 'Fiji' },
  { code: 'FI', iso: 'FI', prefix: '358', nameRu: 'Финляндия', nameEn: 'Finland' },
  { code: 'FR', iso: 'FR', prefix: '33', nameRu: 'Франция', nameEn: 'France' },
  { code: 'GF', iso: 'GF', prefix: '594', nameRu: 'Гвиана', nameEn: 'French Guiana' },
  { code: 'PF', iso: 'PF', prefix: '689', nameRu: 'Французская Полинезия', nameEn: 'French Polynesia' },
  { code: 'GA', iso: 'GA', prefix: '241', nameRu: 'Габон', nameEn: 'Gabon' },
  { code: 'GM', iso: 'GM', prefix: '220', nameRu: 'Гамбия', nameEn: 'Gambia' },
  { code: '995', iso: 'GE', prefix: '995', nameRu: 'Грузия', nameEn: 'Georgia' },
  { code: 'DE', iso: 'DE', prefix: '49', nameRu: 'Германия', nameEn: 'Germany' },
  { code: 'GH', iso: 'GH', prefix: '233', nameRu: 'Гана', nameEn: 'Ghana' },
  { code: 'GI', iso: 'GI', prefix: '350', nameRu: 'Гибралтар', nameEn: 'Gibraltar' },
  { code: 'GR', iso: 'GR', prefix: '30', nameRu: 'Греция', nameEn: 'Greece' },
  { code: 'GL', iso: 'GL', prefix: '299', nameRu: 'Гренландия', nameEn: 'Greenland' },
  { code: 'GD', iso: 'GD', prefix: '1', nameRu: 'Гренада', nameEn: 'Grenada' },
  { code: 'GP', iso: 'GP', prefix: '590', nameRu: 'Гваделупа', nameEn: 'Guadeloupe' },
  { code: 'GU', iso: 'GU', prefix: '1', nameRu: 'Гуам', nameEn: 'Guam' },
  { code: 'GT', iso: 'GT', prefix: '502', nameRu: 'Гватемала', nameEn: 'Guatemala' },
  { code: 'GG', iso: 'GG', prefix: '44', nameRu: 'Гернси', nameEn: 'Guernsey' },
  { code: 'GN', iso: 'GN', prefix: '224', nameRu: 'Гвинея', nameEn: 'Guinea' },
  { code: 'GW', iso: 'GW', prefix: '245', nameRu: 'Гвинея-Бисау', nameEn: 'Guinea-Bissau' },
  { code: 'GY', iso: 'GY', prefix: '592', nameRu: 'Гайана', nameEn: 'Guyana' },
  { code: 'HT', iso: 'HT', prefix: '509', nameRu: 'Гаити', nameEn: 'Haiti' },
  { code: 'VA', iso: 'VA', prefix: '39', nameRu: 'Ватикан', nameEn: 'Vatican' },
  { code: 'HN', iso: 'HN', prefix: '504', nameRu: 'Гондурас', nameEn: 'Honduras' },
  { code: 'HK', iso: 'HK', prefix: '852', nameRu: 'Гонконг', nameEn: 'Hong Kong' },
  { code: 'HU', iso: 'HU', prefix: '36', nameRu: 'Венгрия', nameEn: 'Hungary' },
  { code: 'IS', iso: 'IS', prefix: '354', nameRu: 'Исландия', nameEn: 'Iceland' },
  { code: 'IN', iso: 'IN', prefix: '91', nameRu: 'Индия', nameEn: 'India' },
  { code: 'ID', iso: 'ID', prefix: '62', nameRu: 'Индонезия', nameEn: 'Indonesia' },
  { code: 'IR', iso: 'IR', prefix: '98', nameRu: 'Иран', nameEn: 'Iran' },
  { code: 'IQ', iso: 'IQ', prefix: '964', nameRu: 'Ирак', nameEn: 'Iraq' },
  { code: 'IE', iso: 'IE', prefix: '353', nameRu: 'Ирландия', nameEn: 'Ireland' },
  { code: 'IM', iso: 'IM', prefix: '44', nameRu: 'Остров Мэн', nameEn: 'Isle of Man' },
  { code: 'IL', iso: 'IL', prefix: '972', nameRu: 'Израиль', nameEn: 'Israel' },
  { code: 'IT', iso: 'IT', prefix: '39', nameRu: 'Италия', nameEn: 'Italy' },
  { code: 'JM', iso: 'JM', prefix: '1', nameRu: 'Ямайка', nameEn: 'Jamaica' },
  { code: 'JP', iso: 'JP', prefix: '81', nameRu: 'Япония', nameEn: 'Japan' },
  { code: 'JE', iso: 'JE', prefix: '44', nameRu: 'Джерси', nameEn: 'Jersey' },
  { code: 'JO', iso: 'JO', prefix: '962', nameRu: 'Иордания', nameEn: 'Jordan' },
  { code: '77', iso: 'KZ', prefix: '7', nameRu: 'Казахстан', nameEn: 'Kazakhstan' },
  { code: 'KE', iso: 'KE', prefix: '254', nameRu: 'Кения', nameEn: 'Kenya' },
  { code: 'KI', iso: 'KI', prefix: '686', nameRu: 'Кирибати', nameEn: 'Kiribati' },
  { code: 'KP', iso: 'KP', prefix: '850', nameRu: 'КНДР', nameEn: 'DPRK' },
  { code: 'KR', iso: 'KR', prefix: '82', nameRu: 'Республика Корея', nameEn: 'South Korea' },
  { code: 'KW', iso: 'KW', prefix: '965', nameRu: 'Кувейт', nameEn: 'Kuwait' },
  { code: '996', iso: 'KG', prefix: '996', nameRu: 'Киргизия', nameEn: 'Kyrgyzstan' },
  { code: 'LA', iso: 'LA', prefix: '856', nameRu: 'Лаос', nameEn: 'Lao People\'s Democratic Republic' },
  { code: '371', iso: 'LV', prefix: '371', nameRu: 'Латвия', nameEn: 'Latvia' },
  { code: 'LB', iso: 'LB', prefix: '961', nameRu: 'Ливан', nameEn: 'Lebanon' },
  { code: 'LS', iso: 'LS', prefix: '266', nameRu: 'Лесото', nameEn: 'Lesotho' },
  { code: 'LR', iso: 'LR', prefix: '231', nameRu: 'Либерия', nameEn: 'Liberia' },
  { code: 'LY', iso: 'LY', prefix: '218', nameRu: 'Ливия', nameEn: 'Libyan Arab Jamahiriya' },
  { code: 'LI', iso: 'LI', prefix: '423', nameRu: 'Лихтенштейн', nameEn: 'Liechtenstein' },
  { code: '370', iso: 'LT', prefix: '370', nameRu: 'Литва', nameEn: 'Lithuania' },
  { code: 'LU', iso: 'LU', prefix: '352', nameRu: 'Люксембург', nameEn: 'Luxembourg' },
  { code: 'MO', iso: 'MO', prefix: '853', nameRu: 'Макао', nameEn: 'Macau' },
  { code: 'MK', iso: 'MK', prefix: '389', nameRu: 'Македония', nameEn: 'Macedonia' },
  { code: 'MG', iso: 'MG', prefix: '261', nameRu: 'Мадагаскар', nameEn: 'Madagascar' },
  { code: 'MW', iso: 'MW', prefix: '265', nameRu: 'Малави', nameEn: 'Malawi' },
  { code: 'MY', iso: 'MY', prefix: '60', nameRu: 'Малайзия', nameEn: 'Malaysia' },
  { code: 'MV', iso: 'MV', prefix: '960', nameRu: 'Мальдивы', nameEn: 'Maldives' },
  { code: 'ML', iso: 'ML', prefix: '223', nameRu: 'Мали', nameEn: 'Mali' },
  { code: 'MT', iso: 'MT', prefix: '356', nameRu: 'Мальта', nameEn: 'Malta' },
  { code: 'MH', iso: 'MH', prefix: '692', nameRu: 'Маршалловы Острова', nameEn: 'Marshall Islands' },
  { code: 'MR', iso: 'MR', prefix: '222', nameRu: 'Мавритания', nameEn: 'Mauritania' },
  { code: 'MU', iso: 'MU', prefix: '230', nameRu: 'Маврикий', nameEn: 'Mauritius' },
  { code: 'MX', iso: 'MX', prefix: '52', nameRu: 'Мексика', nameEn: 'Mexico' },
  { code: 'FM', iso: 'FM', prefix: '691', nameRu: 'Микронезия', nameEn: 'Federated States of Micronesia' },
  { code: '373', iso: 'MD', prefix: '373', nameRu: 'Молдавия', nameEn: 'Republic of Moldova' },
  { code: 'MC', iso: 'MC', prefix: '377', nameRu: 'Монако', nameEn: 'Monaco' },
  { code: 'MN', iso: 'MN', prefix: '976', nameRu: 'Монголия', nameEn: 'Mongolia' },
  { code: 'ME', iso: 'ME', prefix: '382', nameRu: 'Черногория', nameEn: 'Montenegro' },
  { code: 'MS', iso: 'MS', prefix: '1', nameRu: 'Монтсеррат', nameEn: 'Montserrat' },
  { code: 'MA', iso: 'MA', prefix: '212', nameRu: 'Марокко', nameEn: 'Morocco' },
  { code: 'MZ', iso: 'MZ', prefix: '258', nameRu: 'Мозамбик', nameEn: 'Mozambique' },
  { code: 'MM', iso: 'MM', prefix: '95', nameRu: 'Мьянма', nameEn: 'Myanmar' },
  { code: 'NA', iso: 'NA', prefix: '264', nameRu: 'Намибия', nameEn: 'Namibia' },
  { code: 'NR', iso: 'NR', prefix: '674', nameRu: 'Науру', nameEn: 'Nauru' },
  { code: 'NP', iso: 'NP', prefix: '977', nameRu: 'Непал', nameEn: 'Nepal' },
  { code: 'NL', iso: 'NL', prefix: '31', nameRu: 'Нидерланды', nameEn: 'Netherlands' },
  { code: 'AN', iso: 'AN', prefix: '599', nameRu: 'Антильские острова', nameEn: 'Netherlands Antilles' },
  { code: 'NC', iso: 'NC', prefix: '687', nameRu: 'Новая Каледония', nameEn: 'New Caledonia' },
  { code: 'NZ', iso: 'NZ', prefix: '64', nameRu: 'Новая Зеландия', nameEn: 'New Zealand' },
  { code: 'NI', iso: 'NI', prefix: '505', nameRu: 'Никарагуа', nameEn: 'Nicaragua' },
  { code: 'NE', iso: 'NE', prefix: '227', nameRu: 'Нигер', nameEn: 'Niger' },
  { code: 'NG', iso: 'NG', prefix: '234', nameRu: 'Нигерия', nameEn: 'Nigeria' },
  { code: 'NU', iso: 'NU', prefix: '683', nameRu: 'Ниуэ', nameEn: 'Niue' },
  { code: 'AP', iso: 'AP', prefix: '', nameRu: 'Азиатско-тихоокеанские территории', nameEn: 'Non-spec Asia Pas Location' },
  { code: 'NF', iso: 'NF', prefix: '672', nameRu: 'Остров Норфолк', nameEn: 'Norfolk Island' },
  { code: 'MP', iso: 'MP', prefix: '1', nameRu: 'Северные Марианские острова', nameEn: 'Northern Mariana Islands' },
  { code: 'NO', iso: 'NO', prefix: '47', nameRu: 'Норвегия', nameEn: 'Norway' },
  { code: 'OM', iso: 'OM', prefix: '968', nameRu: 'Оман', nameEn: 'Oman' },
  { code: 'PK', iso: 'PK', prefix: '92', nameRu: 'Пакистан', nameEn: 'Pakistan' },
  { code: 'PW', iso: 'PW', prefix: '680', nameRu: 'Палау', nameEn: 'Palau' },
  { code: 'PS', iso: 'PS', prefix: '970', nameRu: 'Палестинская национальная администрация', nameEn: 'Palestine' },
  { code: 'PA', iso: 'PA', prefix: '507', nameRu: 'Панама', nameEn: 'Panama' },
  { code: 'PG', iso: 'PG', prefix: '675', nameRu: 'Папуа-Новая Гвинея', nameEn: 'Papua New Guinea' },
  { code: 'PY', iso: 'PY', prefix: '595', nameRu: 'Парагвай', nameEn: 'Paraguay' },
  { code: 'PE', iso: 'PE', prefix: '51', nameRu: 'Перу', nameEn: 'Peru' },
  { code: 'PH', iso: 'PH', prefix: '63', nameRu: 'Филиппины', nameEn: 'Philippines' },
  { code: 'PL', iso: 'PL', prefix: '48', nameRu: 'Польша', nameEn: 'Poland' },
  { code: 'PT', iso: 'PT', prefix: '351', nameRu: 'Португалия', nameEn: 'Portugal' },
  { code: 'PR', iso: 'PR', prefix: '1', nameRu: 'Пуэрто-Рико', nameEn: 'Puerto Rico' },
  { code: 'QA', iso: 'QA', prefix: '974', nameRu: 'Катар', nameEn: 'Qatar' },
  { code: 'ZZ', iso: 'ZZ', prefix: '', nameRu: 'Зарезервировано', nameEn: 'Reserved' },
  { code: 'RE', iso: 'RE', prefix: '262', nameRu: 'Реюньон', nameEn: 'Réunion' },
  { code: 'RO', iso: 'RO', prefix: '40', nameRu: 'Румыния', nameEn: 'Romania' },
  { code: '0', iso: 'RU', prefix: '7', nameRu: 'Россия', nameEn: 'Russian Federation' },
  { code: '374', iso: 'AM', prefix: '374', nameRu: 'Армения', nameEn: 'Armenia' },
  { code: 'RW', iso: 'RW', prefix: '250', nameRu: 'Руанда', nameEn: 'Rwanda' },
  { code: 'KN', iso: 'KN', prefix: '1', nameRu: 'Сент-Китс и Невис', nameEn: 'Saint Kitts and Nevis' },
  { code: 'LC', iso: 'LC', prefix: '1', nameRu: 'Сент-Люсия', nameEn: 'Saint Lucia' },
  { code: 'MF', iso: 'MF', prefix: '590', nameRu: 'Сен-Мартен', nameEn: 'Saint Martin' },
  { code: 'VC', iso: 'VC', prefix: '1', nameRu: 'Сент-Винсент и Гренадины', nameEn: 'Saint Vincent and the Grenadines' },
  { code: 'WS', iso: 'WS', prefix: '685', nameRu: 'Самоа', nameEn: 'Samoa' },
  { code: 'SM', iso: 'SM', prefix: '378', nameRu: 'Сан-Марино', nameEn: 'San Marino' },
  { code: 'SA', iso: 'SA', prefix: '966', nameRu: 'Саудовская Аравия', nameEn: 'Saudi Arabia' },
  { code: 'SN', iso: 'SN', prefix: '221', nameRu: 'Сенегал', nameEn: 'Senegal' },
  { code: 'RS', iso: 'RS', prefix: '381', nameRu: 'Сербия', nameEn: 'Serbia' },
  { code: 'SC', iso: 'SC', prefix: '248', nameRu: 'Сейшельские Острова', nameEn: 'Seychelles' },
  { code: 'SL', iso: 'SL', prefix: '232', nameRu: 'Сьерра-Леоне', nameEn: 'Sierra Leone' },
  { code: 'SG', iso: 'SG', prefix: '65', nameRu: 'Сингапур', nameEn: 'Singapore' },
  { code: 'SK', iso: 'SK', prefix: '421', nameRu: 'Словакия', nameEn: 'Slovakia' },
  { code: 'SI', iso: 'SI', prefix: '386', nameRu: 'Словения', nameEn: 'Slovenia' },
  { code: 'SB', iso: 'SB', prefix: '677', nameRu: 'Соломоновы Острова', nameEn: 'Solomon Islands' },
  { code: 'SO', iso: 'SO', prefix: '252', nameRu: 'Сомали', nameEn: 'Somalia' },
  { code: 'ZA', iso: 'ZA', prefix: '27', nameRu: 'ЮАР', nameEn: 'South Africa' },
  { code: 'ES', iso: 'ES', prefix: '34', nameRu: 'Испания', nameEn: 'Spain' },
  { code: 'LK', iso: 'LK', prefix: '94', nameRu: 'Шри-Ланка', nameEn: 'Sri Lanka' },
  { code: 'PM', iso: 'PM', prefix: '508', nameRu: 'Сен-Пьер и Микелон', nameEn: 'Saint Pierre and Miquelon' },
  { code: 'SD', iso: 'SD', prefix: '249', nameRu: 'Судан', nameEn: 'Sudan' },
  { code: 'SR', iso: 'SR', prefix: '597', nameRu: 'Суринам', nameEn: 'Suriname' },
  { code: 'SZ', iso: 'SZ', prefix: '268', nameRu: 'Свазиленд', nameEn: 'Swaziland' },
  { code: 'SE', iso: 'SE', prefix: '46', nameRu: 'Швеция', nameEn: 'Sweden' },
  { code: 'CH', iso: 'CH', prefix: '41', nameRu: 'Швейцария', nameEn: 'Switzerland' },
  { code: 'SY', iso: 'SY', prefix: '963', nameRu: 'Сирия', nameEn: 'Syria' },
  { code: 'TW', iso: 'TW', prefix: '886', nameRu: 'Тайвань', nameEn: 'Taiwan; Republic of China' },
  { code: '992', iso: 'TJ', prefix: '992', nameRu: 'Таджикистан', nameEn: 'Tajikistan' },
  { code: 'TZ', iso: 'TZ', prefix: '255', nameRu: 'Танзания', nameEn: 'Tanzania' },
  { code: 'TH', iso: 'TH', prefix: '66', nameRu: 'Тайланд', nameEn: 'Thailand' },
  { code: 'TL', iso: 'TL', prefix: '670', nameRu: 'Восточный Тимор', nameEn: 'Timor-Leste' },
  { code: 'TG', iso: 'TG', prefix: '228', nameRu: 'Того', nameEn: 'Togo' },
  { code: 'TK', iso: 'TK', prefix: '690', nameRu: 'Токелау', nameEn: 'Tokelau' },
  { code: 'TO', iso: 'TO', prefix: '676', nameRu: 'Тонга', nameEn: 'Tonga' },
  { code: 'TT', iso: 'TT', prefix: '1', nameRu: 'Тринидад и Тобаго', nameEn: 'Trinidad and Tobago' },
  { code: 'TN', iso: 'TN', prefix: '216', nameRu: 'Тунис', nameEn: 'Tunisia' },
  { code: 'TR', iso: 'TR', prefix: '90', nameRu: 'Турция', nameEn: 'Turkey' },
  { code: 'TM', iso: 'TM', prefix: '993', nameRu: 'Туркменистан', nameEn: 'Turkmenistan' },
  { code: 'TC', iso: 'TC', prefix: '1', nameRu: 'Тёркс и Кайкос', nameEn: 'Turks and Caicos Islands' },
  { code: 'TV', iso: 'TV', prefix: '688', nameRu: 'Тувалу', nameEn: 'Tuvalu' },
  { code: 'UG', iso: 'UG', prefix: '256', nameRu: 'Уганда', nameEn: 'Uganda' },
  { code: '380', iso: 'UA', prefix: '380', nameRu: 'Украина', nameEn: 'Ukraine' },
  { code: 'AE', iso: 'AE', prefix: '971', nameRu: 'ОАЭ', nameEn: 'United Arab Emirates' },
  { code: 'GB', iso: 'GB', prefix: '44', nameRu: 'Великобритания', nameEn: 'Great Britain' },
  { code: 'US', iso: 'US', prefix: '1', nameRu: 'США', nameEn: 'USA' },
  { code: 'UY', iso: 'UY', prefix: '598', nameRu: 'Уругвай', nameEn: 'Uruguay' },
  { code: '998', iso: 'UZ', prefix: '998', nameRu: 'Узбекистан', nameEn: 'Uzbekistan' },
  { code: 'VU', iso: 'VU', prefix: '678', nameRu: 'Вануату', nameEn: 'Vanuatu' },
  { code: 'VE', iso: 'VE', prefix: '58', nameRu: 'Венесуэла', nameEn: 'Venezuela' },
  { code: 'VN', iso: 'VN', prefix: '84', nameRu: 'Вьетнам', nameEn: 'Vietnam' },
  { code: 'VG', iso: 'VG', prefix: '1', nameRu: 'Британские Виргинские острова', nameEn: 'British Virgin Islands' },
  { code: 'VI', iso: 'VI', prefix: '1', nameRu: 'Американские Виргинские острова', nameEn: 'U.S. Virgin Islands' },
  { code: 'WF', iso: 'WF', prefix: '681', nameRu: 'Уоллис и Футуна', nameEn: 'Wallis and Futuna' },
  { code: 'YE', iso: 'YE', prefix: '967', nameRu: 'Йемен', nameEn: 'Yemen' },
  { code: 'ZM', iso: 'ZM', prefix: '260', nameRu: 'Замбия', nameEn: 'Zambia' },
  { code: 'ZW', iso: 'ZW', prefix: '263', nameRu: 'Зимбабве', nameEn: 'Zimbabwe' },
  { code: '840', iso: '', prefix: '7', nameRu: 'Абхазия', nameEn: 'Abkhazia' },
];

// Russian federal subjects (oblasts/republics/krais), children of Russia
// (code "0"). No calling-code prefix of their own - the country-level
// entry (Russia) is what the client's phone-prefix logic reads from.
const RUSSIAN_REGIONS = [
  { code: '22', nameRu: 'Алтайский край', nameEn: 'Altai Territory' },
  { code: '28', nameRu: 'Амурская область', nameEn: 'Amur Region' },
  { code: '29', nameRu: 'Архангельская область', nameEn: 'Arkhangelsk Region' },
  { code: '30', nameRu: 'Астраханская область', nameEn: 'Astrakhan Region' },
  { code: '31', nameRu: 'Белгородская область', nameEn: 'Belgorod Region' },
  { code: '32', nameRu: 'Брянская область', nameEn: 'Bryansk Region' },
  { code: '33', nameRu: 'Владимирская область', nameEn: 'Vladimir Region' },
  { code: '34', nameRu: 'Волгоградская область', nameEn: 'Volgograd Region' },
  { code: '35', nameRu: 'Вологодская область', nameEn: 'Vologda Region' },
  { code: '36', nameRu: 'Воронежская область', nameEn: 'Voronezh Region' },
  { code: '79', nameRu: 'Еврейская АО', nameEn: 'Jewish Autonomous Region' },
  { code: '75', nameRu: 'Забайкальский край', nameEn: 'Zabaykalsk Territory' },
  { code: '37', nameRu: 'Ивановская область', nameEn: 'Ivanovo Region' },
  { code: '38', nameRu: 'Иркутская область', nameEn: 'Irkutsk Region' },
  { code: '7', nameRu: 'Кабардино-Балкарская Республика', nameEn: 'Kabardino-Balkar Republic' },
  { code: '39', nameRu: 'Калининградская область', nameEn: 'Kaliningrad Region' },
  { code: '40', nameRu: 'Калужская область', nameEn: 'Kaluga Region' },
  { code: '41', nameRu: 'Камчатский край', nameEn: 'Kamchatka Territory' },
  { code: '9', nameRu: 'Карачаево-Черкесская Республика', nameEn: 'Karachay-Cherkess Republic' },
  { code: '42', nameRu: 'Кемеровская область', nameEn: 'Kemerovo Region' },
  { code: '43', nameRu: 'Кировская область', nameEn: 'Kirov Region' },
  { code: '44', nameRu: 'Костромская область', nameEn: 'Kostroma Region' },
  { code: '23', nameRu: 'Краснодарский край', nameEn: 'Krasnodar Territory' },
  { code: '24', nameRu: 'Красноярский край', nameEn: 'Krasnoyarsk Territory' },
  { code: '45', nameRu: 'Курганская область', nameEn: 'Kurgan Region' },
  { code: '46', nameRu: 'Курская область', nameEn: 'Kursk Region' },
  { code: '48', nameRu: 'Липецкая область', nameEn: 'Lipetsk Region' },
  { code: '49', nameRu: 'Магаданская область', nameEn: 'Magadan Region' },
  { code: '50', nameRu: 'Москва и Моск. область', nameEn: 'Moscow' },
  { code: '51', nameRu: 'Мурманская область', nameEn: 'Murmansk Region' },
  { code: '83', nameRu: 'Ненецкий АО', nameEn: 'Nenets Autonomous District' },
  { code: '52', nameRu: 'Нижегородская область', nameEn: 'Nizhny Novgorod Region' },
  { code: '53', nameRu: 'Новгородская область', nameEn: 'Novgorod Region' },
  { code: '54', nameRu: 'Новосибирская область', nameEn: 'Novosibirsk Region' },
  { code: '55', nameRu: 'Омская область', nameEn: 'Omsk Region' },
  { code: '56', nameRu: 'Оренбургская область', nameEn: 'Orenburg Region' },
  { code: '57', nameRu: 'Орловская область', nameEn: 'Oryol Region' },
  { code: '58', nameRu: 'Пензенская область', nameEn: 'Penza Region' },
  { code: '59', nameRu: 'Пермский край', nameEn: 'Perm Territory' },
  { code: '25', nameRu: 'Приморский край', nameEn: 'Primorsky Territory' },
  { code: '60', nameRu: 'Псковская область', nameEn: 'Pskov Region' },
  { code: '1', nameRu: 'Республика Адыгея', nameEn: 'Republic of Adygea' },
  { code: '4', nameRu: 'Республика Алтай', nameEn: 'Altai Republic' },
  { code: '2', nameRu: 'Республика Башкортостан', nameEn: 'Republic of Bashkortostan' },
  { code: '3', nameRu: 'Республика Бурятия', nameEn: 'Republic of Buryatia' },
  { code: '5', nameRu: 'Республика Дагестан', nameEn: 'Republic of Dagestan' },
  { code: '6', nameRu: 'Республика Ингушетия', nameEn: 'Republic of Ingushetia' },
  { code: '8', nameRu: 'Республика Калмыкия', nameEn: 'Republic of Kalmykia' },
  { code: '10', nameRu: 'Республика Карелия', nameEn: 'Republic of Karelia' },
  { code: '11', nameRu: 'Республика Коми', nameEn: 'Komi Republic' },
  { code: '12', nameRu: 'Республика Марий Эл', nameEn: 'Mari El Republic' },
  { code: '13', nameRu: 'Республика Мордовия', nameEn: 'Republic of Mordovia' },
  { code: '14', nameRu: 'Республика Саха (Якутия)', nameEn: 'Sakha (Yakutia) Republic' },
  { code: '15', nameRu: 'Республика Северная Осетия', nameEn: 'Republic of North Ossetia' },
  { code: '16', nameRu: 'Республика Татарстан', nameEn: 'Republic of Tatarstan' },
  { code: '17', nameRu: 'Республика Тыва', nameEn: 'Tuva Republic' },
  { code: '18', nameRu: 'Республика Удмуртия', nameEn: 'Udmurt Republic' },
  { code: '19', nameRu: 'Республика Хакасия', nameEn: 'Republic of Khakassia' },
  { code: '61', nameRu: 'Ростовская область', nameEn: 'Rostov Region' },
  { code: '62', nameRu: 'Рязанская область', nameEn: 'Ryazan Region' },
  { code: '63', nameRu: 'Самарская область', nameEn: 'Samara Region' },
  { code: '47', nameRu: 'Санкт-Петербург и Лен. область', nameEn: 'Saint Petersburg' },
  { code: '64', nameRu: 'Саратовская область', nameEn: 'Saratov Region' },
  { code: '65', nameRu: 'Сахалинская область', nameEn: 'Sakhalin Region' },
  { code: '66', nameRu: 'Свердловская область', nameEn: 'Sverdlovsk Region' },
  { code: '67', nameRu: 'Смоленская область', nameEn: 'Smolensk Region' },
  { code: '26', nameRu: 'Ставропольский край', nameEn: 'Stavropol Territory' },
  { code: '68', nameRu: 'Тамбовская область', nameEn: 'Tambov Region' },
  { code: '69', nameRu: 'Тверская область', nameEn: 'Tver Region' },
  { code: '70', nameRu: 'Томская область', nameEn: 'Tomsk Region' },
  { code: '71', nameRu: 'Тульская область', nameEn: 'Tula Region' },
  { code: '72', nameRu: 'Тюменская область', nameEn: 'Tyumen Region' },
  { code: '73', nameRu: 'Ульяновская область', nameEn: 'Ulyanovsk Region' },
  { code: '27', nameRu: 'Хабаровский край', nameEn: 'Khabarovsk Territory' },
  { code: '86', nameRu: 'Ханты-Мансийский АО', nameEn: 'Khanty–Mansi Autonomous District' },
  { code: '74', nameRu: 'Челябинская область', nameEn: 'Chelyabinsk Region' },
  { code: '20', nameRu: 'Чеченская Республика', nameEn: 'Chechen Republic' },
  { code: '21', nameRu: 'Чувашская Республика', nameEn: 'Chuvash Republic' },
  { code: '87', nameRu: 'Чукотский АО', nameEn: 'Chukotka Autonomous District' },
  { code: '89', nameRu: 'Ямало-Ненецкий АО', nameEn: 'Yamalo-Nenets Autonomous District' },
  { code: '76', nameRu: 'Ярославская область', nameEn: 'Yaroslavl Region' },
];

module.exports = { COUNTRIES, RUSSIAN_REGIONS };
